import {places,agenda} from './places.js';
const $ = id => document.getElementById(id);
const base = places.find(p=>p.id==='base');
const people=['Aaron','Harry','Matt','Tom'];
const days=[{n:23,label:'FRI',full:'Friday',subtitle:'Arrivals & darts'},{n:24,label:'SAT',full:'Saturday',subtitle:'Slavia & the night'},{n:25,label:'SUN',full:'Sunday',subtitle:'Sparta day'},{n:26,label:'MON',full:'Monday',subtitle:'The journey home'}];
const safeLoad=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const state={day:23,category:'All',origin:'base',geo:null,search:'',sort:'distance',person:safeLoad('prague26-person',''),ballots:safeLoad('prague26-ballots',{})};
const save=()=>{try{localStorage.setItem('prague26-person',JSON.stringify(state.person));localStorage.setItem('prague26-ballots',JSON.stringify(state.ballots))}catch{toast('Storage is unavailable on this browser.')}};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const timeNow=()=>new Date(new Date().toLocaleString('en-US',{timeZone:'Europe/Prague'}));
const tripNow=()=>{const d=timeNow();return d.getFullYear()===2026&&d.getMonth()===9&&d.getDate()>=23&&d.getDate()<=26?d:null};
function metres(a,b){const rad=Math.PI/180,dLat=(b.lat-a.lat)*rad,dLng=(b.lng-a.lng)*rad,x=Math.sin(dLat/2)**2+Math.cos(a.lat*rad)*Math.cos(b.lat*rad)*Math.sin(dLng/2)**2;return 6371000*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function distance(p){return metres(state.geo||places.find(x=>x.id===state.origin)||base,p)}
function distanceText(p){const m=distance(p);return m<1000?`${Math.round(m/50)*50} m`:`${(m/1000).toFixed(1)} km`}
function votesFor(id){return people.filter(name=>(state.ballots[name]?.picks||[]).includes(id))}
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').classList.remove('visible'),3400)}
function route(p){const origin=state.geo?`${state.geo.lat},${state.geo.lng}`:`${(places.find(x=>x.id===state.origin)||base).lat},${(places.find(x=>x.id===state.origin)||base).lng}`;return `https://www.google.com/maps/dir/?api=1&origin=${encodeURIComponent(origin)}&destination=${p.lat}%2C${p.lng}&travelmode=walking`}
function eventLink(e){return e.place?places.find(p=>p.id===e.place)?.maps:e.link}
function renderDays(){const current=tripNow();if(current)state.day=current.getDate();$('day-tabs').innerHTML=days.map(d=>`<button role="tab" aria-selected="${state.day===d.n}" class="day-tab ${state.day===d.n?'active':''}" data-day="${d.n}"><span>${d.label} <b>${d.n}</b></span><small>${d.subtitle}</small></button>`).join('');renderAgenda()}
function renderAgenda(){const list=agenda.filter(a=>a.day===state.day);$('agenda-list').innerHTML=list.map(e=>`<article class="agenda-item ${e.kind}"><span class="agenda-time">${e.time}</span><span class="agenda-symbol">${e.kind==='football'?'⚽':e.kind==='travel'?'✈':'✦'}</span><div class="agenda-text"><strong>${esc(e.title)}</strong><small>${e.kind==='football'?'MATCHDAY':e.kind==='travel'?'TRAVEL':'EVENING PLAN'}</small></div>${eventLink(e)?`<a href="${esc(eventLink(e))}" target="_blank" rel="noopener noreferrer" aria-label="Open ${esc(e.title)} details">↗</a>`:''}</article>`).join('')||'<p>No fixed plans yet. The day is yours.</p>';$('day-tabs').querySelectorAll('button').forEach(b=>{b.classList.toggle('active',+b.dataset.day===state.day);b.setAttribute('aria-selected',String(+b.dataset.day===state.day))})}
function card(p,compact=false){const names=votesFor(p.id);const voted=names.includes(state.person);return `<article class="place-card ${compact?'compact':''}"><div class="card-top"><span class="category-tag ${p.category.toLowerCase()}">${esc(p.category)}</span><span class="card-distance">◎ ${distanceText(p)}</span></div><div class="place-content"><div class="place-area">${esc(p.area)}</div><h3>${esc(p.name)}</h3><p>${esc(p.note)}</p></div><div class="card-bottom"><span class="vote-count" title="${esc(names.join(', ')||'No votes yet')}">${names.length?'♥ '+names.length+' · '+esc(names.join(', ')):'♡ No votes yet'}</span><div><button class="vote-button ${voted?'selected':''}" data-vote="${esc(p.id)}" aria-label="${voted?'Remove vote for':'Vote for'} ${esc(p.name)}" aria-pressed="${voted}">${voted?'♥':'♡'} Vote</button><a class="maps-button" href="${esc(route(p))}" target="_blank" rel="noopener noreferrer" aria-label="Walking directions to ${esc(p.name)}">Directions ↗</a></div></div>${compact?'':`<a class="venue-link" href="${esc(p.maps)}" target="_blank" rel="noopener noreferrer">View place on Google Maps ↗</a>`}</article>`}
function renderPlaces(){let list=places.filter(p=>p.id!=='base'&&(state.category==='All'||p.category===state.category)&&`${p.name} ${p.area} ${p.note}`.toLowerCase().includes(state.search));list.sort((a,b)=>state.sort==='name'?a.name.localeCompare(b.name):state.sort==='votes'?votesFor(b.id).length-votesFor(a.id).length||distance(a)-distance(b):distance(a)-distance(b));$('result-count').textContent=`${list.length} PLACE${list.length===1?'':'S'} · ${state.geo?'FROM YOUR LOCATION':`FROM ${(places.find(p=>p.id===state.origin)||base).name.toUpperCase()}`}`;$('places-grid').innerHTML=list.length?list.map(p=>card(p)).join(''):'<div class="empty">No places match that search. Try another filter.</div>';renderSuggestions()}
function renderSuggestions(){const now=tripNow();const day=now?now.getDate():23,hour=now?now.getHours():17,mins=now?now.getHours()*60+now.getMinutes():17*60;const next=agenda.find(e=>e.day===day&&(+e.time.slice(0,2)*60 + +e.time.slice(3))>mins);let category=hour<11?'Breakfast':hour<16?'Food':hour>=19?'Nightlife':'All';const until=next?(+next.time.slice(0,2)*60 + +next.time.slice(3))-mins:Infinity;let picks=[];
 if(next?.place&&until<150){const destination=places.find(p=>p.id===next.place);if(destination)picks.push(destination)}
 const pool=places.filter(p=>p.id!=='base'&&p.category!=='Football'&&p.id!==picks[0]?.id).sort((a,b)=>{const score=p=>(p.category===category?0:category==='All'&&p.category==='Chill'?0:1)*100000+distance(p);return score(a)-score(b)});
 picks.push(...pool.slice(0,3-picks.length));$('suggest-context').textContent=now?next&&until<150?`Coming up: ${next.title} at ${next.time}. Here are nearby ideas and the next destination.`:`A few nearby ${category==='All'?'options':category.toLowerCase()+' options'} for ${days.find(d=>d.n===day).full.toLowerCase()}.`:'A preview for the trip. During 23–26 October, these ideas will adapt to the time in Prague.';$('suggest-grid').innerHTML=picks.map(p=>card(p,true)).join('')}
function renderFilters(){$('filters').innerHTML=['All','Breakfast','Food','Nightlife','Chill','Football'].map(c=>`<button class="filter ${state.category===c?'active':''}" data-category="${c}" aria-pressed="${state.category===c}">${c}</button>`).join('')}
function setOrigin(){state.geo=null;state.origin=$('originSelect').value;$('origin-label').textContent=state.origin==='base'?'Our base':places.find(p=>p.id===state.origin)?.name||'Our base';$('locationBtn').classList.remove('active');renderPlaces()}
function addVote(id){if(!state.person){$('personSelect').focus();toast('Choose your name in the voting section first.');$('votes').scrollIntoView({behavior:'smooth'});return}const current=state.ballots[state.person]?.picks||[];state.ballots[state.person]={picks:current.includes(id)?current.filter(v=>v!==id):[...current,id],at:Date.now()};save();renderPlaces();toast(current.includes(id)?'Vote removed. Share updated picks with the group.':'Vote saved. Share your picks with the group.')}
function encodeBallot(payload){return btoa(JSON.stringify(payload)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function importBallot(){const url=new URL(location.href),encoded=url.searchParams.get('ballot');if(!encoded)return;url.searchParams.delete('ballot');history.replaceState(null,'',url.pathname+url.search+url.hash);try{if(encoded.length>1500)throw Error();const raw=JSON.parse(atob(encoded.replace(/-/g,'+').replace(/_/g,'/')));if(!people.includes(raw.name)||!Array.isArray(raw.picks)||raw.picks.length>places.length||!raw.picks.every(id=>places.some(p=>p.id===id))||!Number.isSafeInteger(raw.at))throw Error();const existing=state.ballots[raw.name];if(!existing||raw.at>existing.at){state.ballots[raw.name]={picks:[...new Set(raw.picks)],at:raw.at};save();toast(`${raw.name}'s picks added to this phone.`)}else toast(`You already have ${raw.name}'s latest picks.`)}catch{toast('That ballot link could not be read.')}}
async function shareVotes(){if(!state.person){$('personSelect').focus();toast('Choose your name first.');return}const b=state.ballots[state.person]||{picks:[],at:Date.now()};if(!b.picks.length){toast('Vote for a place first.');return}const url=new URL(location.href);url.searchParams.set('ballot',encodeBallot({name:state.person,...b}));url.hash='votes';const text=`${state.person}'s Prague picks · open this link to add them to your tally`;try{if(navigator.share){await navigator.share({title:'Prague 26 picks',text,url:url.toString()})}else if(navigator.clipboard){await navigator.clipboard.writeText(`${text}\n${url}`);toast('Ballot link copied. Send it in your group chat.')}else{prompt('Copy your ballot link',url.toString())}}catch(e){if(e.name!=='AbortError')toast('Could not share the ballot. Try again.') }}
function init(){importBallot();$('originSelect').innerHTML=`<option value="base">Our base · limehome Prague Halkova</option>`+places.filter(p=>p.id!=='base').map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');$('personSelect').value=state.person;renderFilters();renderDays();renderPlaces();$('day-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-day]');if(b){state.day=+b.dataset.day;renderAgenda()}});$('filters').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(b){state.category=b.dataset.category;renderFilters();renderPlaces()}});document.addEventListener('click',e=>{const b=e.target.closest('[data-vote]');if(b)addVote(b.dataset.vote)});$('originSelect').addEventListener('change',setOrigin);$('search').addEventListener('input',e=>{state.search=e.target.value.toLowerCase().trim();renderPlaces()});$('sortSelect').addEventListener('change',e=>{state.sort=e.target.value;renderPlaces()});$('personSelect').addEventListener('change',e=>{state.person=e.target.value;save();renderPlaces()});$('shareVotes').addEventListener('click',shareVotes);$('suggestBtn').addEventListener('click',()=>$('suggestions').scrollIntoView({behavior:'smooth'}));$('locationBtn').addEventListener('click',()=>{if(!navigator.geolocation){toast('Location is not supported. Choose a place instead.');return}$('locationBtn').textContent='Locating…';navigator.geolocation.getCurrentPosition(pos=>{state.geo={lat:pos.coords.latitude,lng:pos.coords.longitude};$('locationBtn').textContent='◎ Using my location';$('locationBtn').classList.add('active');$('origin-label').textContent='My current location';renderPlaces();toast('Distances updated from your phone.')},()=>{$('locationBtn').textContent='◎ Use my location';toast('Location unavailable. Choose a place as your start instead.')},{enableHighAccuracy:true,timeout:12000,maximumAge:60000})});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})}
init();
